import math
import torch
import torch.nn as nn
import torch.optim as optim
from sklearn.metrics import balanced_accuracy_score
import warnings

# Suppress minor PyTorch warnings for clean terminal output
warnings.filterwarnings("ignore")


class PhaseA_FNN(nn.Module):
    """
    The strictly constrained Neural Network architecture for Phase A (Discovery).
    Topology: 2 Hidden Layers, 64 Neurons per Layer.
    """

    def __init__(self, input_dim, num_classes, activation_func=nn.GELU()):
        super(PhaseA_FNN, self).__init__()

        self.layer1 = nn.Linear(input_dim, 64)
        self.layer2 = nn.Linear(64, 64)
        self.output_layer = nn.Linear(64, num_classes)

        self.activation = activation_func

    def forward(self, x):
        x = self.activation(self.layer1(x))
        x = self.activation(self.layer2(x))
        x = self.output_layer(x)  # CrossEntropyLoss handles the softmax internally
        return x


class PyTorchEvaluator:
    """
    The Inner Loop Wrapper. This takes a dataset and a GP-generated variance,
    injects the variance into the FNN, and trains it to extract fitness scores.
    """

    def __init__(self, dataset_dict, sigma_squared, max_epochs=30, target_acc=0.85):
        self.X_train = dataset_dict['X_train']
        self.y_train = dataset_dict['y_train']
        self.X_val = dataset_dict['X_val']
        self.y_val = dataset_dict['y_val']

        self.input_dim = self.X_train.shape[1]
        self.num_classes = len(torch.unique(self.y_train))

        self.sigma_squared = sigma_squared
        self.max_epochs = max_epochs
        self.target_acc = target_acc

        # Instantiate the model
        self.model = PhaseA_FNN(self.input_dim, self.num_classes)
        self._inject_custom_variance()

    def _inject_custom_variance(self):
        """
        THE CORE THESIS MECHANISM:
        Overrides default PyTorch initializations. Applies a Normal Distribution
        centered at 0, using the standard deviation derived from the GP's sigma^2.
        """
        # Protect against negative variances generated by early, mutated GP equations
        if self.sigma_squared <= 0:
            self.sigma_squared = 1e-5

        std_dev = math.sqrt(self.sigma_squared)

        with torch.no_grad():
            for layer in [self.model.layer1, self.model.layer2, self.model.output_layer]:
                nn.init.normal_(layer.weight, mean=0.0, std=std_dev)
                # Initialize biases to 0 to strictly isolate the effect of weight variance
                nn.init.zeros_(layer.bias)

    def evaluate_fitness(self):
        """
        Executes the short training loop.
        Returns Objective 1 (Balanced Accuracy) and Objective 2 (Epochs-to-Threshold).
        """
        criterion = nn.CrossEntropyLoss()
        optimizer = optim.Adam(self.model.parameters(), lr=0.005)

        epochs_to_threshold = self.max_epochs
        final_val_acc = 0.0

        for epoch in range(self.max_epochs):
            self.model.train()
            optimizer.zero_grad()

            # Forward pass
            outputs = self.model(self.X_train)
            loss = criterion(outputs, self.y_train)

            # Backward pass (Calculate gradients)
            loss.backward()

            # --- GRADIENT EXPLOSION SAFEGUARD (Module 4 Lite) ---
            # If the initialized variance was mathematically doomed, abort early.
            for param in self.model.parameters():
                if param.grad is not None:
                    if torch.isnan(param.grad).any() or torch.isinf(param.grad).any():
                        return 0.0, 999  # 0 Accuracy, 999 Epoch Penalty

            optimizer.step()

            # Validation pass
            self.model.eval()
            with torch.no_grad():
                val_outputs = self.model(self.X_val)
                _, predicted = torch.max(val_outputs, 1)

                # Use Balanced Accuracy to account for class imbalances in the datasets
                val_acc = balanced_accuracy_score(self.y_val.numpy(), predicted.numpy())

                if val_acc >= self.target_acc and epochs_to_threshold == self.max_epochs:
                    epochs_to_threshold = epoch + 1

                final_val_acc = val_acc

        return final_val_acc, epochs_to_threshold


# --- Quick Test Block ---
if __name__ == "__main__":
    from mod_3_dataset_manager import DatasetManager

    # Load just one dataset from your manager to test the injection
    manager = DatasetManager("Phase_A_Discovery_Datasets.csv",
                             r"C:\Users\John Arellano\PycharmProjects\Applied_Comp_Intel_Project\openml_cc18_datasets")
    manager.load_all_to_ram()

    # Grab the first dataset ID (look at your console output to grab a valid ID like 3 or 31)
    test_did = list(manager.dataset_cache.keys())[0]
    dataset, meta_features = manager.get_dataset(test_did)

    # Simulate a GP outputting a variance of 0.05
    test_variance = 0.05

    print(f"\nTesting PyTorch Injection on Dataset {test_did} with Variance: {test_variance}")
    evaluator = PyTorchEvaluator(dataset, sigma_squared=test_variance)
    accuracy, epochs = evaluator.evaluate_fitness()

    print(f"Result: {accuracy * 100:.2f}% Balanced Accuracy achieved.")
    print(f"Speed: Hit threshold in {epochs} epochs.")